[package]
name = "edcfg-lint"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
dashmap = "6.1.0"
ec4rs = "1.2.0"
encoding_rs = "0.8.35"
human-units = "0.5.3"
ignore = "0.4.25"
memchr = "2.7.6"
regex = "1.11.1"
termcolor = "1.4.1"

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0.1.52"

# The `release` and `release-lto` files were borrowed from `ripgrep`.
[profile.release]
debug = 1

[profile.release-lto]
inherits = "release"
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1

[tool.maturin]
profile = "release-lto"
editable-profile = "release"
