name: Rust lint

on:
    push: ~
    pull_request: ~

env:
    CARGO_TERM_COLOR: always

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Cargo fmt
              run: cargo fmt --check
            - name: Clippy
              run: cargo clippy --verbose
